[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["DJ Edmonson <djedmonson@gmail.com>"]


[dependencies]
clap = "*"
time = "*"
image = "*"
num_cpus = "*"
threadpool = "*"
rustc-serialize = "*"
